const payloadServer = (username, data) => {
  return {
    locale: 'en_US',
    remote: '12.213.1.55',
    agent: 'mozzila',
    user: {
      user_id: username,
      estates: {},
      roles: {}
    },
    data
  }
}

const defaultKeyInitialValue = [
  'afdeling_nm',
  'after_cut',
  'bjr',
  'block_nm',
  'block_nm2',
  'block_nm3',
  'contract',
  'created_by',
  'created_dt',
  'cut',
  'dirt',
  'disortasi_worker_cd',
  'do_date',
  'do_number',
  'dobi',
  'driver_nm',
  'ekspedisi_nm',
  'estate_nm',
  'farmer',
  'ffa',
  'first_update',
  'first_w',
  'fresh_fruit',
  'fresh_fruit_kg',
  'garbage',
  'garbage_kg',
  'grade_class',
  'grading_brondolan',
  'grading_brondolan_kg',
  'is_from_tph',
  'is_lefted',
  'janjang_kosong',
  'janjang_kosong_kg',
  'loader_nm',
  'loader_nm_2',
  'loader_nm_3',
  'long_stalk',
  'long_stalk_kg',
  'mill_arrive_dt',
  'mill_nm',
  'moist',
  'mt_vndr_rent_vhcle_cd',
  'netto_w',
  'nfc_id',
  'overripe_brondolan',
  'overripe_brondolan_kg',
  'overripe_fruit',
  'overripe_fruit_kg',
  'pcc_customer_cd',
  'pcc_mill_cd',
  'pcc_estate_cd',
  'pcc_estate_level_cd',
  'pcc_estate_level_cd2',
  'pcc_estate_level_cd3',
  'pcc_evacuation_activity_cd',
  'pcc_vehicle_cd',
  'pcc_wrkr_cd_driver',
  'pcc_wrkr_cd_loader',
  'pcc_wrkr_cd_loader_2',
  'pcc_wrkr_cd_loader_3',
  'pv',
  'remark1',
  'restan_overnight',
  'restan_overnight_kg',
  'sand_fruit',
  'sand_fruit_kg',
  'seal_number',
  'second_w',
  'spb_date',
  'spb_number',
  'spb_weight',
  'supplier',
  'total_brondolan',
  'total_bunch',
  'total_loaded_nfc',
  'updated_dt',
  'updated_by',
  'upload_flag',
  'water',
  'water_kg',
  'wb_arrive_dt',
  'wb_created_by',
  'wb_created_dt',
  'young_fruit',
  'young_fruit_kg'
]

export { payloadServer, defaultKeyInitialValue }
