const label = {
  actions: 'Aksi',
  wb_arrive_dt: 'Tanggal Masuk',
  first_update: 'Tanggal Keluar',
  comodity_nm: 'Komoditi',
  estate_nm: 'Estate',
  block_nm: 'Subblock',
  pcc_vehicle_cd: 'No. Polisi',
  driver_nm: 'Nama Supir',
  first_w: 'Timbangan Pertama',
  second_w: 'Timbangan Kedua',
  netto_w: 'Netto',
  total_bunch: 'Jumlah Tandan',
  ekspedisi_nm: 'Ekspedisi',
  customer_nm: 'Customer',
  supplier: 'Supplier',
  seal_number: 'No. Seal',
  cut: 'Potongan',
  after_cut: 'Setelah Potongan',
  bjr: 'BJR',
  fresh_fruit: 'Buah Mentah (Tdn)',
  fresh_fruit_kg: 'Buah Mentah (Kg)',
  overripe_fruit: 'Buah Busuk (Tdn)',
  overripe_fruit_kg: 'Buah Busuk (Kg)',
  young_fruit: 'Buah Muda (Tdn)',
  young_fruit_kg: 'Buah Muda (Kg)',
  sand_fruit: 'Buah Pasir (Tdn)',
  sand_fruit_kg: 'Buah Pasir (Kg)',
  long_stalk: 'Tangkai Panjang (Tdn)',
  long_stalk_kg: 'Tangkai Panjang (Kg)',
  janjang_kosong: 'Janjang Kosong (Tdn)',
  janjang_kosong_kg: 'Janjang Kosong (Kg)',
  water: 'TBS Berair (%)',
  water_kg: 'TBS Berair (Kg)',
  grading_brondolan: 'Brondolan (%)',
  grading_brondolan_kg: 'Brondolan (Kg)',
  overripe_brondolan: 'Brondolan Busuk (%)',
  overripe_brondolan_kg: 'Brondolan Busuk (Kg)',
  restan_overnight: 'Restan Overnight (%)',
  restan_overnight_kg: 'Restan Overnight (Kg)',
  garbage: 'Sampah (%)',
  garbage_kg: 'Sampah (Kg)'
}

export { label }
